server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;  # Asegúrate de que este sea el directorio correcto
        try_files $uri $uri/ /index.html;  # Permitir que Angular maneje el enrutamiento
    }
}