version: '3.8'

services:
  db:
    image:  mysql
    environment:
      MYSQL_DATABASE: 'Inventario'
      MYSQL_USER: 'yavirac'
      MYSQL_PASSWORD: 'yaviracAplication'
      MYSQL_ROOT_PASSWORD: 'yaviracAplication'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - desarrollo
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  app:
    image: proyecto:1
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - '8080:8080'
    networks:
      - desarrollo

volumes:
  my-db:

networks:
  desarrollo:
    driver: bridge